name: xdesigner
favicon: null
layout_spectrum: 0
typography_spectrum: 0.90571
title: Alex Hsiao
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ff8f00'
    - '#2f2f31'
    - '#bbbbbb'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
